# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Node / npm
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    versioning-strategy: increase
    schedule:
      interval: "weekly"
      
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/packages/dsl-java" # Location of package manifests
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: /packages/case-connector
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-core-plugin-http-dsl
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-core-plugin-http
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-core
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-entities
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-example-mock-types
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-maintainer-config
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/case-plugin-base
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/contract-case-cli
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/contract-case-jest
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/documentation
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/dsl-java
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/eslint-config-case-maintainer
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /packages/test-equivalence-matchers
    schedule:
      interval: daily
