on:
  push:
    branches: [main]

name: Test Coveralls

jobs:
  build:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit

      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18.x

      - name: Set up JDK 17
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          java-version: '17'
          distribution: 'temurin'
      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@db19848a5fa7950289d3668fb053140cf3028d43 # pin@v3.3.2
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@db19848a5fa7950289d3668fb053140cf3028d43 # v3.3.2
      - run: npm install -g npm@latest

      - name: test
        run: |
          ./ci/coverage.sh
        env:
          CASE_BROKER_CI_TOKEN: ${{ secrets.PACTFLOW_TOKEN }}
          CASE_BROKER_BASEURL: https://timothyjones.pactflow.io/
          FORCE_COLOR: true

      - name: Coveralls Core
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
        with:
          path-to-lcov: 'packages/case-core/combined-coverage.info'
          base-path: 'packages/case-core'
          github-token: ${{ secrets.GITHUB_TOKEN }}
